name = "liberi"
version = "0.1.0"
license = "license"
author = "liberi-devs"
maintainer = "jorgegalvez1694@gmail.com"
copyright = "Copyright 2025, LibERI-devs"
[preprocess]
[preprocess.cpp]
suffixes = ["F90", "f90"]
[build]
auto-executables = false
auto-tests = true
auto-examples = false
module-naming = false
external-modules = ["mpi_f08", "mpi", "mdi"]

[[executable]]
name = "bench_c2h6"
source-dir = "benchmarks"
main = "bench_c2h6.F90"

[[executable]]
name = "bench_c60"
source-dir = "benchmarks"
main = "bench_c60.F90"

[[test]]
name = "test_h2_ccpvdz"
source-dir = "tests/fortran"
main = "test_h2_ccpvdz.F90"

[[test]]
name = "test_h2_sonly"
source-dir = "tests/fortran"
main = "test_h2_sonly.F90"

[[test]]
name = "test_h2o_ccpvdz"
source-dir = "tests/fortran"
main = "test_h2o_ccpvdz.F90"
[install]
library = true
test = false
[fortran]
implicit-typing = false
implicit-external = false
source-form = "free"


[dependencies]
#pic = { git = "https://github.com/JorgeG94/pic.git", tag = "v0.2.0"}
#pic-mpi = { git = "https://github.com/JorgeG94/pic-mpi.git", tag = "v0.1.1"}
#pic-blas = { git = "https://github.com/JorgeG94/pic-blas.git", tag = "v0.2.0"}
#tblite = { git = "https://github.com/tblite/tblite", tag = "v0.5.0"}
#test-drive.git = "https://github.com/JorgeG94/test-drive"
#json-fortran = { git = "https://github.com/jacobwilliams/json-fortran.git", tag = "9.2.0"}
openmp = "*"
[extra.fortitude.check]
select = ["C", "E", "S", "PORT"]
# S212 is the warning that a program and a module are in the same file, this would make our tests stupid
# C003 is 'implicit none' missing 'external', this does not always work with other compilers, so we ignore it
# C072 is character '{name}' has assumed size but does not have intent(in), since this is a bit too much
ignore = ["C003", "C072", "S212"]
line-length = 132
